---
driver:
  name: docker_cli
  use_sudo: false
  remove_images: true
  container_name: vlc_compilator
  privileged: false
  network: bridge

transport:
  name: docker_cli

provisioner:
  name: chef_solo
  require_chef_omnibus: false
  chef_solo_path: '/usr/bin/chef-solo'

platforms:
  - name: debian
    driver_config:
      image: "arm_box-debian"
      platform: ubuntu
      hostname: vlc
      envirionment:
        TERM: 'xterm'
suites:
  - name: default
    run_list:
      - recipe[docker_vlc::default]
    attributes: